---
title: "CodeBook"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#CODE BOOK

This is a code book that describes the variables, the data, and the transformations I performed to clean up the data.

### Data Source
•	Original data: https://d396qusza40orc.cloudfront.net/getdata%2Fprojectfiles%2FUCI%20HAR%20Dataset.zip

•	Description of the dataset:http://archive.ics.uci.edu/ml/datasets/Human+Activity+Recognition+Using+Smartphones

### Data Set Information

The experiments have been carried out with a group of 30 volunteers within an age bracket of 19-48 years. Each person performed six activities (WALKING, WALKING UPSTAIRS, WALKING DOWNSTAIRS, SITTING, STANDING, LAYING) wearing a smartphone (Samsung Galaxy S II) on the waist. 
Using its embedded accelerometer and gyroscope, we captured 3-axial linear acceleration and 3-axial angular velocity at a constant rate of 50Hz. The experiments have been video-recorded to label the data manually.
The obtained dataset has been randomly partitioned into two sets, where 70% of the volunteers was selected for generating the training data and 30% the test data.

The sensor signals (accelerometer and gyroscope) were pre-processed by applying noise filters and then sampled in fixed-width sliding windows of 2.56 sec and 50% overlap (128 readings/window). The sensor acceleration signal, which has gravitational and body motion components, was separated using a Butterworth low-pass filter into body acceleration and gravity. The gravitational force is assumed to have only low frequency components, therefore a filter with 0.3 Hz cutoff frequency was used. From each window, a vector of features was obtained by calculating variables from the time and frequency domain.

### The data

The dataset includes the files:

•	'README.txt'

•	'features_info.txt': Shows information about the variables used on the feature vector.

•	'features.txt': List of all features.

•	'activity_labels.txt': Links the class labels with their activity name.

•	'train/X_train.txt': Training set.

•	'train/y_train.txt': Training labels.

•	'test/X_test.txt': Test set.

•	'test/y_test.txt': Test labels.

The following files are available for the train and test data. Their descriptions are equivalent.

•	'train/subject_train.txt': Each row identifies the subject who performed the activity for each window sample. Its range is from 1 to 30.

•	'train/Inertial Signals/total acc x train.txt': The acceleration signal from the smartphone accelerometer X axis in standard gravity units 'g'. Every row shows a 128 element vector. The same description applies for the 'total acc x train.txt' and 'total acc z train.txt' files for the Y and Z axis.

•	'train/Inertial Signals/body acc x train.txt': The body acceleration signal obtained by subtracting the gravity from the total acceleration.

•	'train/Inertial Signals/body gyro x train.txt': The angular velocity vector measured by the gyroscope for each window sample. The units are radians/second.

### Description of the DATA

The features selected for this database come from the accelerometer and gyroscope 3-axial raw signals tAcc-XYZ and tGyro-XYZ. These time domain signals (prefix ‘t’ to denote time) were captured at a constant rate of 50 Hz. and the acceleration signal was then separated into body and gravity acceleration signals (tBodyAcc-XYZ and tGravityAcc-XYZ) – both using a low pass Butterworth filter.

The body linear acceleration and angular velocity were derived in time to obtain Jerk signals (tBodyAccJerk-XYZ and tBodyGyroJerk-XYZ). Also the magnitude of these three-dimensional signals were calculated using the Euclidean norm (tBodyAccMag, tGravityAccMag, tBodyAccJerkMag, tBodyGyroMag, tBodyGyroJerkMag).

A Fast Fourier Transform (FFT) was applied to some of these signals producing fBodyAcc-XYZ, fBodyAccJerk-XYZ, fBodyGyro-XYZ, fBodyAccJerkMag, fBodyGyroMag, fBodyGyroJerkMag. (Note the ‘f’ to indicate frequency domain signals). 

Description of abbreviations of measurements

1.	leading t or f is based on time or frequency measurements.

2.	Body = related to body movement.

3.	Gravity = acceleration of gravity

4.	Acc = accelerometer measurement

5.	Gyro = gyroscopic measurements

6.	Jerk = sudden movement acceleration

7.	Mag = magnitude of movement

8.	mean and SD are calculated for each subject for each activity for each mean and SD measurements.

The units given are g’s for the accelerometer and rad/sec for the gyro and g/sec and rad/sec/sec for the corresponding jerks.

These signals were used to estimate variables of the feature vector for each pattern:
‘-XYZ’ is used to denote 3-axial signals in the X, Y and Z directions. They total 33 measurements including the 3 dimensions - the X,Y, and Z axes.

•	tBodyAcc-XYZ

•	tGravityAcc-XYZ

•	tBodyAccJerk-XYZ

•	tBodyGyro-XYZ

•	tBodyGyroJerk-XYZ

•	tBodyAccMag

•	tGravityAccMag

•	tBodyAccJerkMag

•	tBodyGyroMag

•	tBodyGyroJerkMag

•	fBodyAcc-XYZ

•	fBodyAccJerk-XYZ

•	fBodyGyro-XYZ

•	fBodyAccMag

•	fBodyAccJerkMag

•	fBodyGyroMag

•	fBodyGyroJerkMag


The set of variables that were estimated from these signals are:

•	mean(): Mean value

•	std(): Standard deviation

### Transformation 

The project is divided in 5 parts:

1.	Merges the training and the test sets to create one data set.

2.	Extracts only the measurements on the mean and standard deviation for each measurement.

3.	Uses descriptive activity names to name the activities in the data set

4.	Appropriately labels the data set with descriptive activity names.

5.	Creates a second, independent tidy data set with the average of each variable for each activity and each subject.


